name: POS Local
values:
  - key: baseUrl
    value: 'http://localhost/Tienda'
    type: default
    enabled: true
  - key: usuario
    value: admin
    type: default
    enabled: true
  - key: password
    value: 'password'
    type: secret
    enabled: true
  - key: barcode
    value: '7501234567890'
    type: default
    enabled: true
